services:
  # 1. Брокер
  redis:
    image: redis:7-alpine
    container_name: cv_redis
    ports:
      - "6379:6379"

  # 2. API
  api:
    build: .
    container_name: cv_api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # 3. Worker
  worker:
    build: .
    container_name: cv_worker
    # Запускаем Celery
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data
      - .:/app 
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # 4. Client
  frontend:
    build: .
    container_name: cv_frontend
    command: streamlit run frontend/app.py --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - API_URL=http://api:8000 
    depends_on:
      - api